[package]
name = "addition"
version = "0.1.0"
edition = "2021"

[features]
ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { version = "0.13.2", features = ["ndarray", "wgpu"] }
