[package]
edition.workspace = true
license.workspace = true
version.workspace = true
name = "addition"
publish = false

[features]
ndarray = ["burn/ndarray"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { version = "0.13.2", features = ["ndarray", "wgpu"] }
